version: "3"
services:
  next-app:
    build:
      context: .
      args:
        NEXT_PUBLIC_BASE_URL: "http://qrnx.ru"
    image: ${IMAGE_NAME}
    container_name: next_app
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "3000:3000"

    environment:
      - NEXT_PUBLIC_BASE_URL=http://qrnx.ru
