name: Auto PR Title from Branch

on:
  pull_request:
    types: [opened]

jobs:
  set-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Extract task-tracker ID and update PR title
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          
          # Extract task-tracker number (format: username/task-tracker-number/description)
          TASK_TRACKER=$(echo "$BRANCH_NAME" | cut -d'/' -f2)

          # Ensure it follows the expected pattern
          if [[ "$TASK_TRACKER" =~ ^[A-Za-z]+-[0-9]+$ ]]; then
            PR_TITLE="${TASK_TRACKER}: "
            PR_NUMBER="${{ github.event.pull_request.number }}"
            gh pr edit $PR_NUMBER --title "$PR_TITLE"
          else
            echo "Branch name format is incorrect. Skipping title update."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
